# Generated by Django 5.0.1 on 2024-01-13 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("estores", "0002_alter_products_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="products",
            name="product_name",
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name="products",
            name="slug",
            field=models.SlugField(max_length=200, unique=True),
        ),
    ]
