# Generated by Django 5.0.1 on 2024-01-14 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("estores", "0004_alter_products_options_variations"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="variations",
            options={
                "ordering": ["-created_date"],
                "verbose_name": "Variations",
                "verbose_name_plural": "Variations",
            },
        ),
        migrations.AddIndex(
            model_name="variations",
            index=models.Index(
                fields=["-created_date"], name="estores_var_created_958f2d_idx"
            ),
        ),
    ]
