# Generated by Django 5.0.1 on 2024-01-14 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("estores", "0005_alter_variations_options_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Variations",
            new_name="Variation",
        ),
        migrations.RenameIndex(
            model_name="variation",
            new_name="estores_var_created_72916b_idx",
            old_name="estores_var_created_958f2d_idx",
        ),
    ]
