# Generated by Django 4.1.5 on 2024-01-20 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("estores", "0010_alter_variation_variation_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="variation",
            name="variation_category",
            field=models.CharField(
                choices=[("color", "color"), ("size", "size")], max_length=100
            ),
        ),
    ]
