# Generated by Django 5.0.1 on 2024-01-14 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("estores", "0006_rename_variations_variation_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="variation",
            options={
                "ordering": ["-created_date"],
                "verbose_name": "Variation",
                "verbose_name_plural": "Variations",
            },
        ),
    ]
