# Generated by Django 4.1.5 on 2024-01-20 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("estores", "0009_alter_variation_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="variation",
            name="variation_category",
            field=models.CharField(
                choices=[("colors", "colors"), ("sizes", "sizes")], max_length=100
            ),
        ),
    ]
