# Generated by Django 4.1.5 on 2024-01-20 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("carts", "0004_cartitem_user_alter_cartitem_cart"),
    ]

    operations = [
        migrations.AddField(
            model_name="cart",
            name="cart_name",
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
