# Generated by Django 5.0.1 on 2024-01-20 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_alter_orderproducts_options"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="phone_number",
            new_name="phone",
        ),
        migrations.AlterField(
            model_name="order",
            name="order_number",
            field=models.CharField(max_length=20),
        ),
    ]
