# Generated by Django 5.0.1 on 2024-01-23 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("estores", "0011_alter_variation_variation_category"),
        ("orders", "0005_remove_orderproducts_color_remove_orderproducts_size"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orderproducts",
            name="variation",
        ),
        migrations.AddField(
            model_name="orderproducts",
            name="variation",
            field=models.ManyToManyField(blank=True, to="estores.variation"),
        ),
    ]
