# Generated by Django 5.0.1 on 2024-01-16 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_account_token"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="account",
            name="token",
        ),
        migrations.AlterField(
            model_name="account",
            name="last_login",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="last login"
            ),
        ),
    ]
