# Generated by Django 5.0.1 on 2024-01-16 23:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_remove_account_token_alter_account_last_login"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="date_login",
            field=models.DateField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
