# Generated by Django 5.0.1 on 2024-01-13 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("carts", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="cart",
            old_name="card_id",
            new_name="cart_id",
        ),
    ]
