# Generated by Django 5.0.1 on 2024-01-14 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("carts", "0002_rename_card_id_cart_cart_id"),
        ("estores", "0009_alter_variation_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="cartitem",
            name="variation",
            field=models.ManyToManyField(blank=True, to="estores.variation"),
        ),
    ]
